"""requirements.txt is the pip fallback for source-mode machines without uv.

It must stay the exact export of uv.lock, or a machine on the pip path (old
capnhat.bat, or setup.bat when uv cannot be installed) runs other versions than
CI tested.
"""

from pathlib import Path
import shutil
import subprocess

import pytest


ROOT = Path(__file__).resolve().parents[1]
EXPORT_COMMAND = ["uv", "export", "--format", "requirements.txt", "--no-dev", "--locked", "--quiet"]


def requirement_lines(text):
    """The export without its "autogenerated by" comment header."""
    lines = text.replace("\r\n", "\n").splitlines()
    while lines and lines[0].startswith("#"):
        lines.pop(0)
    return lines


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv is not on PATH")
def test_requirements_txt_is_the_export_of_uv_lock():
    # --locked also fails when uv.lock no longer matches pyproject.toml.
    exported = subprocess.run(
        EXPORT_COMMAND,
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=120,
        check=False,
    )
    assert exported.returncode == 0, exported.stderr

    committed = (ROOT / "requirements.txt").read_text(encoding="utf-8")
    assert requirement_lines(committed) == requirement_lines(exported.stdout), (
        "requirements.txt is out of date; regenerate it with "
        "`uv export --format requirements.txt --no-dev --locked -o requirements.txt`"
    )
